/**
 * Shared strict-JSON parsing helpers for LLM structured output.
 *
 * These parse the *entire* response as JSON (after stripping one optional
 * ```json fence) and reject anything that doesn't match the expected shape.
 * Permissive alias handling (e.g. accepting legacy field names for old
 * persisted data) belongs in the callers that deal with historical records,
 * NOT here — new generations should fail strict and trigger a repair retry.
 */

export function stripJsonFence(content: string): string {
  let text = content.trim();
  const fenceMatch = text.match(/^```(?:json)?\s*\n?([\s\S]*?)\n?\s*```$/);
  if (fenceMatch) {
    text = fenceMatch[1].trim();
  }
  return text;
}

export function parseJsonValue(content: string): unknown {
  try {
    return JSON.parse(stripJsonFence(content)) as unknown;
  } catch {
    return null;
  }
}

export function parseJsonObject(content: string): Record<string, unknown> | null {
  const parsed = parseJsonValue(content);
  if (typeof parsed === 'object' && parsed !== null && !Array.isArray(parsed)) {
    return parsed as Record<string, unknown>;
  }
  return null;
}

export function parseStringArray(content: string): string[] | null {
  const parsed = parseJsonValue(content);
  if (Array.isArray(parsed) && parsed.every((s) => typeof s === 'string')) {
    return parsed as string[];
  }
  return null;
}

export interface ParsedChecklistGroup {
  title: string;
  items: { content: string; details?: string }[];
}

/**
 * Parses a checklist generated by the LLM. Expected shape:
 * `{ "groups": [{ "title": "...", "items": [{ "content": "...", "details": "..." }] }] }`.
 * Returns null when the structure is invalid so the caller can retry.
 */
export function parseChecklistGroups(content: string): ParsedChecklistGroup[] | null {
  const parsed = parseJsonObject(content);
  if (!parsed) return null;

  const groups = parsed.groups ?? parsed.lists;
  if (!Array.isArray(groups)) return null;

  const result: ParsedChecklistGroup[] = [];
  for (const g of groups) {
    if (typeof g !== 'object' || g === null) return null;
    const record = g as Record<string, unknown>;
    const title = typeof record.title === 'string' ? record.title.trim() : '';
    const rawItems = record.items ?? record.tasks;
    if (!Array.isArray(rawItems)) return null;

    const items: { content: string; details?: string }[] = [];
    for (const it of rawItems) {
      if (typeof it === 'string') {
        const content = it.trim();
        if (!content) return null;
        items.push({ content });
        continue;
      }
      if (typeof it !== 'object' || it === null) return null;
      const itemRecord = it as Record<string, unknown>;
      const content =
        typeof itemRecord.content === 'string'
          ? itemRecord.content.trim()
          : typeof itemRecord.text === 'string'
            ? itemRecord.text.trim()
            : '';
      if (!content) return null;
      const details = typeof itemRecord.details === 'string' ? itemRecord.details.trim() : undefined;
      items.push({ content, ...(details ? { details } : {}) });
    }
    result.push({ title, items });
  }

  return result;
}
